# Generated by Django 4.2.3 on 2023-07-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTest',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=355, unique=True)),
                ('rdate', models.DateTimeField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'account_test',
                'managed': False,
            },
        ),
    ]
